main: net.staticcraft.setwarp.SetWarp
name: SetWarp
version: '1.3'
description: Allows you to set some warps for yourself
api-version: '1.13'
commands:
  setpwarp:
    description: Set a warp
  delpwarp:
    description: Delete a warp
  pwarp:
    description: Go to a warp
  listpwarps:
    description: Lists all your current warps